server.port = 2000

spring.datasource.url = jdbc:mysql://localhost:3306/document?useSSL=false&allowPublicKeyRetrieval=true&jdbcCompliantTruncation=false
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.datasource.Security=com.mysql.jdbc.driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

upload.directory=C:/Users/2000080631/workspace/UploadedFiles